---
#sdk: "../../../../rhodes"
name: new_orm_spec
applog: RhoLogSpec.txt
version: 1.1
app_type: "rhoelements"
vendor: rhomobile
sdkversion: 4.1

wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
iphone:
  configuration: "Release"
  sdk: "iphoneos8.2"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.newormspec"
  BundleURLScheme: "newormspec"
wp:
  productid: 'fd55c4d0-51fa-012e-7844-6caec51bd50e'

android:
  version: 4.4.2

extensions:
- mspec
- fileutils
- json
